package com.carbonara.gardenadvisor.ai.prompt;

public class ConstPrompt {

  public static final String RETURN_WEATHER =
      "Given the weather and location data provide the following information in JSON format:\n"
          + " - a \"location\" object, containing the location data, such as name, region and country\n"
          + " - a \"weather\" object, containing the weather forecast (min and max temperatures and weather conditions for today and the next 6 days)\n"
          + " - the output json must respect the following JSON schema:\n"
          + "{\n"
          + "  \"location\": {\n"
          + "    \"name\": \"nameOfLocation\",\n"
          + "    \"region\": \"regionOfLocationIfFoundElseNull\",\n"
          + "    \"country\": \"countryOfLocationIfFoundElseNull\"\n"
          + "  },\n"
          + "  \"weather\": {\n"
          + "    \"forecast\": [\n"
          + "      {\n"
          + "        \"date\": \"YYYY-MM-DD\",\n"
          + "        \"min_temp\": 0.0,\n"
          + "        \"max_temp\": 0.0,\n"
          + "        \"conditions\": \"WeatherConsditionsToParseFromDataPassed\"\n"
          + "      }, ...\n"
          + "    ]\n"
          + "  }\n"
          + "}"
          + "\n Important notice: DO NOT PRINT ANY THING ELSE BUT THE JSON ASKED as a plain text without any Markdown formatting please";
  public static final String RETURN_SUGGESTIONS =
      "Given this location and weather data, provide an answer in Json format with a list of recommended fruits, vegetables and flowers that can be planted at this time, with each value having:\n"
          + "\n"
          + "recommended: boolean value if can be planted now\n"
          + "positives: a list of the positive factors of the weather data\n"
          + "cautions: a list of what i need to be careful when planting\n"
          + "suggestions: a list of possible improvements to get a better result given some suggestions\n"
          + " the output json must respect the following JSON schema:\n"
          + "{\n"
          + "  \"fruits\": [\n"
          + "    {\n"
          + "      \"name\": \"NameOfFruit\",\n"
          + "      \"recommended\": true if is recommended else false,\n"
          + "      \"positives\": [\n"
          + "        \"APositiveSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"cautions\": [\n"
          + "        \"ACautionSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"suggestions\": [\n"
          + "        \"AGeneralSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ]\n"
          + "    },\n...]"
          + "  \"vegetables\": [\n"
          + "    {\n"
          + "      \"name\": \"NameOfVegetable\",\n"
          + "      \"recommended\": true if is recommended else false,\n"
          + "      \"positives\": [\n"
          + "        \"APositiveSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"cautions\": [\n"
          + "        \"ACautionSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"suggestions\": [\n"
          + "        \"AGeneralSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ]\n"
          + "    },\n...]"
          + "  \"flowers\": [\n"
          + "    {\n"
          + "      \"name\": \"NameOfFlower\",\n"
          + "      \"recommended\": true if is recommended else false,\n"
          + "      \"positives\": [\n"
          + "        \"APositiveSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"cautions\": [\n"
          + "        \"ACautionSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"suggestions\": [\n"
          + "        \"AGeneralSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ]\n"
          + "    },\n...]"
          + "}\n"
          + "\n Important notice: DO NOT PRINT ANY THING ELSE BUT THE JSON ASKED as a plain text without any Markdown formatting please";
}
