package com.carbonara.gardenadvisor.ai.prompt;

public class ConstPrompt {

  public static final String RETURN_WEATHER =
      "Given the weather and location data provide the following information in JSON format:\n"
          + " - a \"location\" object, containing the location data, such as name, region and country\n"
          + " - a \"weather\" object, containing the weather forecast (min and max temperatures and weather conditions for today and the next 6 days)\n"
          + " - for every weather object calculate the best icon to show between this 10 icons:\n"
          + "    - bad_clouds (1)\n"
          + "    - clouds (2)\n"
          + "    - clouds_thunder (3)\n"
          + "    - fog (4)\n"
          + "    - rain (5)\n"
          + "    - snow (6)\n"
          + "    - sun (7)\n"
          + "    - sun_cloud (8)\n"
          + "    - sun_cloud_rain (9)\n"
          + "    - thunder (10)\n"
          + " - the output json must respect the following JSON schema:\n"
          + "{\n"
          + "  \"location\": {\n"
          + "    \"name\": \"nameOfLocation\",\n"
          + "    \"region\": \"regionOfLocationIfFoundElseNull\",\n"
          + "    \"country\": \"countryOfLocationIfFoundElseNull\"\n"
          + "  },\n"
          + "  \"weather\": {\n"
          + "    \"todayForecast\": {\n"
          + "        \"date\": \"YYYY-MM-DD\",\n"
          + "        \"current_temp\": 0.0,\n"
          + "        \"min_temp\": 0.0,\n"
          + "        \"max_temp\": 0.0,\n"
          + "        \"icon\": number of icon to choose in ex: 2\n"
          + "        \"conditions\": \"WeatherConsditionsToParseFromDataPassed\"\n"
          + "      }\n"
          + "    \"forecast\": [\n"
          + "      {\n"
          + "        \"date\": \"YYYY-MM-DD\",\n"
          + "        \"current_temp\": 0.0,\n"
          + "        \"min_temp\": 0.0,\n"
          + "        \"max_temp\": 0.0,\n"
          + "        \"icon\": number of icon to choose in ex: 4\n"
          + "        \"conditions\": \"WeatherConsditionsToParseFromDataPassed\"\n"
          + "      }, ...\n"
          + "    ]\n"
          + "  }\n"
          + "}\n"
          + " Important notice: DO NOT PRINT ANY THING ELSE BUT THE JSON ASKED as a plain text without any Markdown formatting please\n"
          + "Notice that today is:";
  public static final String RETURN_SUGGESTIONS =
      "Given this location and weather data, provide an answer in Json format with a list of recommended fruits, vegetables and flowers that can be planted at this time, with each value having:\n"
          + "\n"
          + "recommended: boolean value if can be planted now\n"
          + "recommendedScore: an integer value score from 1 to 5 representing how recommended it is to plant"
          + "maintenanceScore: an integer value score from 1 to 5 representing how difficult it is to maintain\n"
          + "positives: a list of the positive factors of the weather data\n"
          + "cautions: a list of what i need to be careful when planting\n"
          + "suggestions: a list of possible improvements to get a better result given some suggestions\n"
          + " the output json must respect the following JSON schema:\n"
          + "{\n"
          + "  \"fruits\": [\n"
          + "    {\n"
          + "      \"name\": \"NameOfFruit\",\n"
          + "      \"recommended\": true if is recommended else false,\n"
          + "      \"recommendedScore\": integer value from 1 to 5 of how recommended it is to plant,\n"
          + "      \"maintenanceScore\": integer value from 1 to 5 of how difficult it is to maintain,\n"
          //          + "      \"imageUrl\": \"anUrlOfAnImageForThePlantSpecified\",\n"
          + "      \"positives\": [\n"
          + "        \"APositiveSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"cautions\": [\n"
          + "        \"ACautionSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"suggestions\": [\n"
          + "        \"AGeneralSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ]\n"
          + "    },\n...]"
          + "  \"vegetables\": [\n"
          + "    {\n"
          + "      \"name\": \"NameOfVegetable\",\n"
          //          + "      \"imageUrl\": \"anUrlOfAnImageForThePlantSpecified\",\n"
          + "      \"recommended\": true if is recommended else false,\n"
          + "      \"recommendedScore\": integer value from 1 to 5 of how recommended it is to plant,\n"
          + "      \"maintenanceScore\": integer value from 1 to 5 of how difficult it is to maintain,\n"
          + "      \"positives\": [\n"
          + "        \"APositiveSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"cautions\": [\n"
          + "        \"ACautionSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"suggestions\": [\n"
          + "        \"AGeneralSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ]\n"
          + "    },\n...]"
          + "  \"flowers\": [\n"
          + "    {\n"
          + "      \"name\": \"NameOfFlower\",\n"
          //          + "      \"imageUrl\": \"anUrlOfAnImageForThePlantSpecified\",\n"
          + "      \"recommended\": true if is recommended else false,\n"
          + "      \"recommendedScore\": integer value from 1 to 5 of how recommended it is to plant,\n"
          + "      \"maintenanceScore\": integer value from 1 to 5 of how difficult it is to maintain,\n"
          + "      \"positives\": [\n"
          + "        \"APositiveSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"cautions\": [\n"
          + "        \"ACautionSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ],\n"
          + "      \"suggestions\": [\n"
          + "        \"AGeneralSuggestionBasedOnCurrentPlantAndCurrentOrFutureWeather\",\n..."
          + "      ]\n"
          + "    },\n...]"
          + "}\n"
          + "\n Important notice: DO NOT PRINT ANY THING ELSE BUT THE JSON ASKED as a plain text without any Markdown formatting please";
}
