name: Build Debug APK


on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


# on:
#  push:
#   branches:
   # - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Get keys.properties from secrets 
      run: echo "${{secrets.KEYS_PROPERTIES_FILE }}" > $GITHUB_WORKSPACE/keys.properties 
    
    - name: Gradle check
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: check

    - name: Build Debug APK
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: APK(s) debug generated
        path: app/build/outputs/apk/debug/
